import validators
from flask import send_file

from core.ProcessedItem import ProcessedItem
from core.images_utils import get_image_path_by_id
from core.utils import read_json_from_file, write_json_to_file
from web_interface.backend.controllers.settings import get_settings
from web_interface.backend.settings import image_data_schema_file_path


def _get_data_schema():
    return read_json_from_file(image_data_schema_file_path, False)


def _create_data_schema() -> dict:
    schema = ProcessedItem.model_json_schema()

    write_json_to_file(schema, image_data_schema_file_path, True, True)

    return schema


def get_images_list():
    settings = get_settings().core
    try:
        data_json = read_json_from_file(settings.data_file)
    except FileNotFoundError:
        return []

    return [id_ for id_ in data_json.keys()]


def get_image(image_id):
    settings = get_settings().core
    image_path = get_image_path_by_id(image_id, settings.images_folder)
    if not image_path:
        raise KeyError(f"Image with id '{image_id}' not found.")

    return send_file(image_path, mimetype="image/jpeg")


def create_image(data: dict):
    for key in ["url", "id"]:
        if key not in data.keys():
            raise KeyError(f"Key '{key}' is not provided.")
    if not validators.url(data["url"]):
        raise ValueError(f"Url '{data['url']}' is not valid.")

    settings = get_settings()
    ProcessedItem(_settings=settings, id=data["id"], title="", media=data["url"]).save(
        fall_on_fail=True
    )


def get_image_model(image_id, image_data: dict = None) -> ProcessedItem:
    settings = get_settings()
    data_json = read_json_from_file(settings.core.data_file)
    image_data = image_data or data_json[str(image_id)]
    item = ProcessedItem(**image_data)
    item._settings = settings

    return item


def get_image_data(image_id) -> dict:
    return get_image_model(image_id).model_dump(mode="json")


def get_image_data_schema():
    return _get_data_schema() or _create_data_schema()


def set_image_data(image_id, data):
    model = get_image_model(image_id, data)
    model.save()

    return model.model_dump()


def generate_image_description(image_id: str):
    get_image_model(image_id).describe(fall_if_failed=True)


def delete_image(image_id: str):
    get_image_model(image_id).delete()


def process_by_gpt(image_id: str):
    image_model = get_image_model(image_id)
    gpt_text, result = image_model.gpt(fall_if_failed=True)

    if gpt_text is None:
        raise Exception(
            "GPT text was not generated by service provided. Try again or use another service."
        )


def to_webp(image_id: str):
    get_image_model(image_id).to_webp()


def optimize_image(image_id: str):
    get_image_model(image_id).minimize()


def gpt2json(image_id: str):
    get_image_model(image_id).gpt2json(fall_if_failed=True)


def cartoonize(image_id: str):
    get_image_model(image_id).cartoonize()
